using System;

namespace EditorTools.SerializedReferenceInitializer.Attributes
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class AutoGeneratedWrapperAttribute : Attribute
    {
        /// <summary>
        /// The  Unity object class type that this wrapper wraps.
        /// </summary>
        public Type WrappedType { get; }
        
        public AutoGeneratedWrapperAttribute(Type wrappedType)
        {
            WrappedType = wrappedType;
        }
    }
}