namespace EditorTools.SerializedReferenceInitializer.Example.Implementations
{
    using UnityEngine;
    using System;
    using EditorTools.SerializedReferenceInitializer.Attributes;
    
    
    [SerializableAttribute()]
    [AutoGeneratedWrapperAttribute(typeof(EditorTools.SerializedReferenceInitializer.Example.Implementations.SingingDog))]
    internal sealed class SingingDog_ISing_Wrapper : EditorTools.SerializedReferenceInitializer.Example.ISing
    {
        
        [SerializeField()]
        private EditorTools.SerializedReferenceInitializer.Example.Implementations.SingingDog _instance;
        
        private SingingDog_ISing_Wrapper(EditorTools.SerializedReferenceInitializer.Example.Implementations.SingingDog instance)
        {
            this._instance = instance;
        }
        
        public void Sing()
        {
            this._instance.Sing();
        }
        
        public void StopSinging()
        {
            this._instance.StopSinging();
        }
    }
}
