namespace EditorTools.SerializedReferenceInitializer.Example.Implementations
{
    using UnityEngine;
    using System;
    using EditorTools.SerializedReferenceInitializer.Attributes;
    
    
    [SerializableAttribute()]
    [AutoGeneratedWrapperAttribute(typeof(EditorTools.SerializedReferenceInitializer.Example.Implementations.StreetPerformer))]
    internal sealed class StreetPerformer_ISing_Wrapper : EditorTools.SerializedReferenceInitializer.Example.ISing
    {
        
        [SerializeField()]
        private EditorTools.SerializedReferenceInitializer.Example.Implementations.StreetPerformer _instance;
        
        private StreetPerformer_ISing_Wrapper(EditorTools.SerializedReferenceInitializer.Example.Implementations.StreetPerformer instance)
        {
            this._instance = instance;
        }
        
        public void Sing()
        {
            this._instance.Sing();
        }
        
        public void StopSinging()
        {
            this._instance.StopSinging();
        }
    }
}
